### ISSUE TITLE
建议改一下定时，被警告了，早上太早了，没有活动记录，改到10点，都在上班了  差不多

### ISSUE THREAD

**Issue by fadeds** [leochen-g/ql-juejinhelper#4]
![image](https://user-images.githubusercontent.com/27796945/211708299-73c507b3-49b5-4ff2-ab5d-549c0b5ef49d.png)

**Comment by fadeds** [comment]
或者在跑任务之前  浏览几篇文章，查看几条沸点

**Comment by fadeds** [comment]
或者再加个随机定时，不要固定一个时间运行

**Comment by fadeds** [comment]
> 已接受最新PR

原作者的仓库已更新稳定，可以看着添加模拟用户活跃度

**Comment by leochen-g** [comment]
已更新
