### ISSUE TITLE
AxiosError: Request failed with status code 404!

### ISSUE THREAD

**Issue by WeYouHe** [leochen-g/ql-juejinhelper#8]
掘金-海底掘金, 失败! 原因: AxiosError: Request failed with status code 404!

青龙面板2.11.3版本
突然运行报错

**Comment by JiZhiLieShou** [comment]
日志-掘金-海底掘金
## 开始执行... 2023-08-22 10:22:15


🔔掘金-海底掘金, 开始!

====================共1个掘金账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2023/8/22 10:22:15=====================


❌ 掘金-海底掘金, 失败! 原因: AxiosError: Request failed with status code 404!


🔔掘金-海底掘金, 结束! 🕛 6.316 秒


## 执行结束... 2023-08-22 10:22:21 耗时 6 秒

**Comment by leochen-g** [comment]
海底掘金已下线，脚本已更新
